### ISSUE TITLE
【每周算法】258. 各位相加 —— leetcode

### ISSUE THREAD

**Issue by pzqu** [coding3min/coding3min#2]
给定一个非负整数 `num`，反复将各个位上的数字相加，直到结果为一位数。

示例:
```
输入: 38
输出: 2 
解释: 各位相加的过程为：3 + 8 = 11, 1 + 1 = 2。 由于 2 是一位数，所以返回 2。
```
进阶:
你可以不使用循环或者递归，且在 O(1) 时间复杂度内解决这个问题吗？

https://leetcode-cn.com/problems/add-digits/

**Comment by wangxun-Jack** [comment]
class Solution {
	public int addDigits(int number) {
		int divisor = 1;//除数
		String strValue = Integer.toString(number);
		int len = strValue.length();//位数
		if (1 == len)
		{
			return number;
		}
		for (int i = 1; i <= len-1; i++)
		{
			divisor = divisor * 10;
		}
		int sum = 0;//求和
		int consult;
		int remainder;
		int tmp = number;
		do {
			consult = tmp / divisor;//商
			remainder = tmp % divisor;//余数
			divisor = divisor/10;
			sum = sum + consult;
			tmp = remainder;
		}while(0 != remainder);
		sum = addDigits(sum);
		return sum;		
	}
}

**Comment by muggleCY** [comment]
//自己最开始的做法
var addDigits = function(num) {
    var num1 = 0;
    var num2 = 0;
    while(num > 9){
        num1 = num%10;
        num2 +=num1;
        num = Math.floor(num/10);
        if(num < 10){
            num += num2;
            num2 = 0;
        }
    }
    return num;
};
//结合对于一般整数来说直接对整数进行对9求余，便可得到小于10的结果。除非整除另外考虑
var addDigits = function(num) {
    if(num == 0){
        return 0;
    }
    var i = num%9;
    if(i == 0){
        return 9;
    }else{
        return i;
    }
};

**Comment by pzqu** [comment]
赞！代码的语法可以用数字键1左边的连续三个反引号前后包住，效果如下
```c++
printf("ok")
```

使用方法
![image](https://user-images.githubusercontent.com/42294819/69008748-08bd1380-0989-11ea-9740-2c09f20fecaa.png)
